yml #5

diff --git a/.github/workflows/ci-javascript-samples.yml b/.github/workflows/ci-javascript-samples.yml
--- a/.github/workflows/ci-javascript-samples.yml
+++ b/.github/workflows/ci-javascript-samples.yml
@@ -1,7 +1,7 @@
 name: ci-javascript-samples
 
 env:
-  ROOT_FOLDER: samples/javascript_nodejs/02.echo-bot
+  ROOT_FOLDER: BotBuilder-Samples/samples/javascript_nodejs/02.echo-bot
 
 on:
   workflow_dispatch:
@@ -9,36 +9,101 @@ on:
     branches:
       - main
     paths:
-      - "samples/javascript_nodejs/02.echo-bot/**"
+      - "samples/**/*.js"
+      - "samples/**/*.ts"
 
 jobs:
-  build:
+  generate:
+    name: detect and generate bot matrix
     runs-on: ubuntu-latest
-    name: Build Echo Bot
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
 
-      - name: Use Node.js 18.x
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: git diff
+        uses: technote-space/get-diff-action@v4
+        with:
+          PATTERNS: samples/**/*.+(ts|js)
+          ABSOLUTE: true
+
+      - name: generate matrix
+        id: set-matrix
+        shell: pwsh
+        if: env.GIT_DIFF
+        run: |
+          function UpSearchFolder {
+            param ([String] $path, [String] $file)
+
+            while ($path -and !(Test-Path (Join-Path $path $file))) {
+              $path = Split-Path $path -Parent
+            }
+
+            return $path
+          }
+
+          $paths = @("${{ env.GIT_DIFF_FILTERED }}" -replace "'", "" -split " ")
+          $rootFolder = "${{ env.ROOT_FOLDER }}"
+          $pkg = "package.json"
+
+          $result = $paths | ForEach-Object { UpSearchFolder -path $_ -file $pkg } | Get-Unique | ForEach-Object {
+            $folder = $_
+            $json = Get-Content -Raw -Path (Join-Path $folder $pkg) | ConvertFrom-Json
+            $files = @($paths | Where-Object { $_.StartsWith($folder) })
+            return @{ 
+              name = $folder.Substring($folder.IndexOf($rootFolder) + $rootFolder.Length);
+              scripts = @($json.scripts | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name);
+              folder = $folder;
+              files = $files
+            } 
+          }
+
+          "Generated matrix:"
+          ConvertTo-Json @($result)
+
+          $matrix = ConvertTo-Json -Compress @($result)
+
+          echo "::set-output name=matrix::$($matrix)"
+
+  build:
+    needs: generate
+    runs-on: ubuntu-latest
+    strategy:
+      matrix: 
+        include: ${{fromJSON(needs.generate.outputs.matrix)}}
+      fail-fast: false
+
+    name: bot - ${{ matrix.name }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: use node 18.x
         uses: actions/setup-node@v3
         with:
           node-version: 18.x
-          working-directory: ${{ env.ROOT_FOLDER }}
+
+      - name: Check if package.json exists
+        run: |
+          if [ ! -f package.json ]; then
+            echo "Error: package.json not found!"
+            exit 1
+          fi
 
       - name: Install dependencies
         run: npm install
-        working-directory: ${{ env.ROOT_FOLDER }}
+        working-directory: ${{ matrix.folder }}
 
       - name: Build project (if applicable)
-        run: npm run build
-        if: test -f package.json && jq -e .scripts.build package.json > /dev/null
-        working-directory: ${{ env.ROOT_FOLDER }}
+        run: |
+          if [ -f package.json ] && jq -e .scripts.build package.json > /dev/null; then
+            npm run build
+          fi
+        working-directory: ${{ matrix.folder }}
 
-      - name: Run ESLint
-        run: npx eslint .
-        working-directory: ${{ env.ROOT_FOLDER }}
-
-      - name: Run tests (if applicable)
-        run: npm test
-        if: test -f package.json && jq -e .scripts.test package.json > /dev/null
-        working-directory: ${{ env.ROOT_FOLDER }}
+      - name: Lint project
+        run: |
+          if [ -f package.json ] && jq -e .scripts.lint package.json > /dev/null; then
+            npm run lint
+          fi
+        working-directory: ${{ matrix.folder }}
